ood_dataset:
  name: conf_ood
  dataset_class: ImglistDataset
  transform: mnist_test_standard
  interpolation: bilinear
  batch_size: 128
  shuffle: False
  num_classes: 10
  image_size: 32
  num_workers: '@{num_workers}'
  split_names: [val]
  val:
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/objects/test_Imagenet_resize1.txt
