name: ood
channels:
  - pytorch
  - conda-forge
dependencies:
  - python=3.8
  - pytorch=1.8.1
  - torchvision=0.9.1
  - cudatoolkit=10.1
  - scikit-learn=0.24.2
  - json5=0.9.6
  - pip
  - pip:
    - pyyaml==5.4.1
    - pre-commit
