dataset:
  name: tin
  split_names: [train, val, test]
  num_classes: 200
  image_size: 32
  num_workers: '@{num_workers}'
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/objects/train_tin_new.txt
    batch_size: 128
    shuffle: True
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/test_tin_new.txt
    batch_size: 200
    shuffle: False
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/test_tin_new.txt
    batch_size: 200
    shuffle: False
    interpolation: bilinear
