dataset:
  name: cifar10
  split_names: [train, val]
  num_classes: 10
  image_size: 32
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  normal_class: 3
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/objects/train_cifar10_id_3.txt
    batch_size: 16
    shuffle: True
    transform: mnist_train_standard
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/objects/train_cifar10_3.txt
    batch_size: 16
    shuffle: False
    transform: mnist_test_standard
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/objects/train_cifar10_3.txt
    batch_size: 16
    shuffle: False
    transform: mnist_test_standard
    interpolation: bilinear
