ood_dataset:
  name: digits_benchmark
  dataset_class: ImglistDataset
  transform: mnist_test_standard
  interpolation: bilinear

  batch_size: 128
  shuffle: True
  num_classes: 10
  image_size: 28
  num_workers: '@{num_workers}'
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]

  split_names: [val, csid, nearood, farood]
  val:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/digits/val_notmnist.txt
  csid:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    datasets: [usps, svhn]
    usps:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_usps.txt
    svhn:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_svhn.txt
  nearood:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    datasets: [notmnist, fashionmnist]
    notmnist:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_notmnist.txt
    fashionmnist:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_fashionmnist.txt
  farood:
    mean: [0.5, 0.5, 0.5]
    std: [0.5, 0.5, 0.5]
    datasets: [texture, cifar10, tin, places365]
    texture:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_texture.txt
    cifar10:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_cifar10.txt
    tin:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_tin.txt
    places365:
      mean: [0.5, 0.5, 0.5]
      std: [0.5, 0.5, 0.5]
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_places365.txt
