dataset:
  name: mvtec
  split_names: [patch, test]
  num_classes: 10
  image_size: 256
  crop_size: 224
  mean: [0.485, 0.456, 0.406]
  std: [0.229, 0.224, 0.225]
  num_workers: '@{num_workers}'
  patch:
    dataset_class: ImglistDataset
    data_dir: ./data/
    imglist_pth: ./data/mvtecList/hazelnut_train_good.txt
    batch_size: 32
    shuffle: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    transform: mnist_train_standard
    interpolation: bilinear

  test:
    dataset_class: ImglistDataset
    data_dir: ./data/
    imglist_pth: ./data/mvtecList/hazelnut_test_good.txt
    batch_size: 32
    shuffle: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    transform: mnist_train_standard
    interpolation: bilinear

ood_dataset:
  name: mvtec
  num_classes: 10
  image_size: 256
  crop_size: 224
  num_workers: 4
  mean: [0.5, 0.5, 0.5]
  std: [0.5, 0.5, 0.5]
  dataset_class: ImglistDataset
  interpolation: bilinear
  batch_size: 32
  shuffle: False

  split_names: [nearood, farood]
  val:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    data_dir: ./data/
    imglist_pth: ./data/mvtecList/hazelnut_test.txt
  nearood:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    datasets: [mvtec]
    mvtec:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      data_dir: ./data/
      imglist_pth: ./data/mvtecList/hazelnut_test.txt
  farood:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    mean: [0.485, 0.456, 0.406]
    std: [0.229, 0.224, 0.225]
    datasets: [mvtec]
    mvtec:
      mean: [0.485, 0.456, 0.406]
      std: [0.229, 0.224, 0.225]
      data_dir: ./data/
      imglist_pth: ./data/mvtecList/hazelnut_test.txt

