dataset:
  name: mvtec
  split_names: [patch, patchTest, patchTestGood, patchGT]
  num_classes: 10
  image_size: 256
  num_workers: '@{num_workers}'
  patch:
    dataset_class: ImglistDataset
    data_dir: ./data/
    imglist_pth: ./data/mvtecList/hazelnut_train_good.txt
    batch_size: 32
    shuffle: False
    transform: mnist_train_standard
    interpolation: bilinear

  patchGT:
    dataset_class: ImglistDataset
    data_dir: ./data/
    imglist_pth: ./data/mvtecList/hazelnut_ground_truth.txt
    batch_size: 32
    shuffle: False
    transform: mnist_train_standard
    interpolation: bilinear
    
  patchTest:
    dataset_class: ImglistDataset
    data_dir: ./data/
    imglist_pth: ./data/mvtecList/hazelnut_test.txt
    batch_size: 32
    shuffle: False
    transform: mnist_train_standard
    interpolation: bilinear

  patchTestGood:
    dataset_class: ImglistDataset
    data_dir: ./data/
    imglist_pth: ./data/mvtecList/hazelnut_test_good.txt
    batch_size: 32
    shuffle: False
    transform: mnist_train_standard
    interpolation: bilinear

ood_dataset:
  name: mvtec
  num_classes: 10
  image_size: 256
  num_workers: 4
  dataset_class: ImglistDataset
  interpolation: bilinear
  batch_size: 32
  shuffle: False

  split_names: [nearood, farood]
  val:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    data_dir: ./data/
    imglist_pth: ./data/mvtecList/hazelnut_test.txt
  nearood:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    datasets: [mvtec]
    mvtec:
      data_dir: ./data/
      imglist_pth: ./data/mvtecList/hazelnut_test.txt
  farood:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    datasets: [mvtec]
    mvtec:
      data_dir: ./data/
      imglist_pth: ./data/mvtecList/hazelnut_test.txt

