dataset:
  name: mvtec
  split_names: [train, trainGT, test, val]
  num_classes: 10
  image_size: 224
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/mvtecList/leather_train_good.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear

  trainGT:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/mvtecList/leather_ground_truth.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear

  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/mvtecList/leather_test_good0.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear

  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/mvtecList/leather_test_good0.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear

ood_dataset:
  name: mvtec
  num_classes: 10
  image_size: 256
  num_workers: 4
  dataset_class: ImglistDataset
  interpolation: bilinear
  batch_size: 32
  shuffle: False

  split_names: [val, nearood, farood]
  val:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/mvtecList/leather_test.txt
  nearood:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    datasets: [mvtec]
    mvtec:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/mvtecList/leather_test.txt
  farood:
    dataset_class: ImglistDataset
    transform: mnist_train_standard
    interpolation: bilinear
    batch_size: 32
    shuffle: True
    datasets: [mvtec]
    mvtec:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/mvtecList/leather_test.txt
