network:
  name: conf_net
  num_classes: '@{dataset.num_classes}'
  pretrained: False # In training pipeline:"False"; In testing pipeline:"True"
  num_gpus: '@{num_gpus}'

  backbone:
    name: lenet
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: True
    checkpoint: ./results/mnist_lenet_conf_esti/best.pth
    num_gpus: '@{num_gpus}'
