network:
  name: mos
  num_classes: '@{dataset.num_classes}'
  model: BiT-S-R101x1
  num_block_open: 0
  bit_pretrained_dir: bit_pretrained_models
  num_logits: 1008
  pretrained: False          # set 'True' to load pretrained model
  checkpoint:          # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
