network:
  name: reactnet
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False
  checkpoint: none           # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
  similarity_measure: 'cosine' # value in ['cosine', 'inner', 'euclid']

  # network used for feature extraction
  backbone:
    name: resnet50
    num_classes: '@{dataset.num_classes}'
    image_size: '@{dataset.image_size}'
    pretrained: True
    checkpoint: './checkpoints/resnet50-0676ba61-pytorch.pth'
    num_gpus: '@{num_gpus}'
