network:
  name: res18
  num_classes: '@{dataset.num_classes}'
  image_size: '@{dataset.image_size}'
  pretrained: False        # set 'True' to load pretrained model
  checkpoint: none         # ignore if pretrained is false
  num_gpus: '@{num_gpus}'
