exp_name: "'@{dataset.name}'_'@{network.name}'_'@{pipeline.name}'\
_'@{evaluator.name}'_'@{postprocessor.name}'\
_'@{postprocessor.postprocessor_args.alpha_list}'"

postprocessor:
  name: gmm
  postprocessor_args:
    num_clusters_list: [3, 1, 10]
    feature_type_list: [stat, mean, flat]     # flat/mean/stat
    alpha_list: [-0.0000000001, 0, 1]
    reduce_dim_list: [none, none, none]   # none/capca_10/pca_50
