postprocessor:
  name: mds
  APS_mode: True
  postprocessor_args:
    noise: 0.0014
    feature_type_list: [mean, mean, mean]     # flat/mean/stat
    alpha_list: #[0, 0, 1]
    reduce_dim_list: [none, none, pca_50]   # none/capca/pca_50/lda
  postprocessor_sweep:
    noise_list: [0.0014]
