dataset:
  name: osr_tin20_seed4
  split_names: [train, val, test]
  num_classes: 20
  pre_size: 64
  image_size: 64
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_tin20/train/train_tin_20_seed4.txt
    batch_size: 128
    shuffle: True
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_tin20/val/val_tin_20_seed4.txt
    batch_size: 200
    shuffle: False
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_tin20/test/test_tin_20_id_seed4.txt
    batch_size: 200
    shuffle: False
    interpolation: bilinear
