ood_dataset:
  name: tin20_osr
  dataset_class: ImglistDataset
  interpolation: bilinear

  batch_size: 128
  shuffle: False
  num_classes: 20
  image_size: 64
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [val, osr]
  val:
    data_dir: ./data/images_classic/
    imglist_pth: ./data/benchmark_imglist/osr_tin20/test/test_tin_20_id_seed1.txt
  osr:
    datasets: [tin_180]
    tin_180:
      data_dir: ./data/images_classic/
      imglist_pth: ./data/benchmark_imglist/osr_tin20/test/test_tin_180_ood_seed1.txt
