exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'"
output_dir: ./results/
save_output: True
force_merge: False

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0

pipeline:
  name: train

trainer:
  name: mos
  group_config: group_config/cifar100_group_config.npy
  num_group: 20

evaluator:
  name: mos

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.003

recorder:
  name: base
  save_all_models: True
