exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'_e'@{optimizer.num_epochs}'_lr'@{optimizer.lr}'"
output_dir: ./results/
save_output: True
force_merge: False

num_gpus: 1
num_workers: 0
num_machines: 1
machine_rank: 0

pipeline:
  name: train

trainer:
  name: mos
  # group_config: ./data/group_config/cifar10_group_config.txt
  group_config: None # if set to none the program will re-compute it

evaluator:
  name: mos

optimizer:
  name: sgd
  num_epochs: 100
  lr: 0.003

recorder:
  name: base
  save_all_models: True
