exp_name: "'@{dataset.name}'_'@{network.name}'_'@{trainer.name}'"
output_dir: ./results/
save_output: True
force_merge: False # disabled if 'save_output' is False
normal_class: 3 #use @ may let int -->str
lamda: 0.01
dataset_name: '@{dataset.name}'
direction_loss_only: False
learning_rate: 1e-3
metrics: roc_auc
last_checkpoint: 201
continue_train: False
num_workers: 0
pipeline:
  name: train_ad
evaluator:
  name: kdad
trainer:
  name: kdad
recorder:
  name: kdad
  save_all_models: False
optimizer:
  num_epochs: 201
