ood_dataset:
  name: imagenet_ood
  dataset_class: ImglistDataset
  interpolation: bilinear
  batch_size: 32
  shuffle: False
  num_classes: 1000
  image_size: 224
  num_workers: '@{num_workers}'
  split_names: [val, nearood]
  val:
    data_dir: ./data/images/
    imglist_pth: ./data_lists/imagenet2012_val_list.txt
  nearood:
    datasets: [inaturalist, openimageo]
    inaturalist:
      dataset_class: ImglistDataset
      data_dir: ./data/iNaturalist/images/
      imglist_pth: ./data/iNaturalist/imglist.txt
    openimageo:
      dataset_class: ImglistDataset
      data_dir: ./data/openimage_clean/images/
      imglist_pth: ./data/openimage_clean/openimage_clean.txt
    imageneto:
      dataset_class: ImglistDataset
      data_dir: ./data/imagenet-o/
      imglist_pth: ./data/imagenet-o/imagenet-o.txt
  farood:
    datasets: [texture]
    texture:
      dataset_class: ImglistDataset
      data_dir: ./data/Texture_clean/images/
      imglist_pth: ./data/Texture_clean/texture_clean.txt
