dataset:
  name: imagenet
  split_names: [train, val, test]
  num_classes: 1000
  image_size: 224
  num_workers: '@{num_workers}'
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data_lists/imagenet2012_train_random_200k.txt
    batch_size: 32
    shuffle: True
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data_lists/imagenet2012_val_list.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data_lists/imagenet2012_val_list.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear
