dataset:
  name: imagenet
  split_names: [train, val, test]
  num_classes: 1000
  image_size: 256
  num_workers: '@{num_workers}'
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data_lists/train_imagenet.txt
    batch_size: 32
    shuffle: True
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/val_imagenet.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/val_ImageNet.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear
