dataset:
  name: bottle
  num_classes: 2
  image_size: 256
  num_workers: 4

  split_names: [train, test]
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    interpolation: bilinear
    imglist_pth: ./data/imglist/mvtec/train/train_bottle.txt
    batch_size: 2
    shuffle: True
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    interpolation: bilinear
    imglist_pth: ./data/imglist/mvtec/test/id/test_bottle_id.txt
    batch_size: 1
    shuffle: False

ood_dataset:
  name: bottle_ood
  num_classes: 2
  image_size: 256
  num_workers: 4

  dataset_class: ImglistDataset
  interpolation: bilinear
  batch_size: 1
  shuffle: False

  split_names: [val]
  val:
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/mvtec/test/ood/test_bottle_ood.txt
