dataset:
  name: bottle
  num_classes: 2
  image_size: 256
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  split_names: [train, test, val]
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    interpolation: bilinear
    imglist_pth: ./data/imglist/mvtec/train/train_bottle.txt
    batch_size: 2
    shuffle: True
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    interpolation: bilinear
    imglist_pth: ./data/imglist/mvtec/test/id/test_bottle_id.txt
    batch_size: 1
    shuffle: False
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    interpolation: bilinear
    imglist_pth: ./data/imglist/mvtec/test/id/test_bottle_id.txt
    batch_size: 1
    shuffle: False

ood_dataset:
  name: bottle_ood
  dataset_class: ImglistDataset
  interpolation: bilinear

  batch_size: 1
  shuffle: False
  num_classes: 2
  image_size: 256
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'

  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/mvtec/test/ood/test_bottle_ood.txt
  nearood:
    datasets: [test_bottle_ood]
    test_bottle_ood:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/mvtec/test/ood/test_bottle_ood.txt
  farood:
    datasets: [test_bottle_ood]
    test_bottle_ood:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/mvtec/test/ood/test_bottle_ood.txt
