name: covid_baseline

dataset:
  # Training datasets
  benchmark: COVID
  train_id: cohen
  image_size: 224

  # Datasets to validate on after every epoch
  # choices: [cifar10, texture, svhn, cifar100, tin, lsun, places365]
  test_ood: [tin]
  labeled_batch_size: 32
  test_batch_size: 200

network: res18L # choices: [lenet_rgb, lenet_bw, res18, wrn, densenet]

trainer_name: base
trainer_args:
  placeholder: placeholder

optim_args:
  epochs: 50
  learning_rate: 0.001
  momentum: 0.9
  weight_decay: 0.0005
