id_dataset: mnist
val_dataset: notmnist
csid_datasets: [usps, svhn]
nearood_datasets: [notmnist, fashionmnist]
farood_datasets: [texture, cifar10, tin, places365]

data_dir: ./data/

# Whether to evaluate each dataset individually, or combine them all altogether
eval_method: each # choices: [each, full]
batch_size: 200
# Type of interpolation when resizing images
interpolation: bilinear # choices: [nearest, bilinear]
image_size: 28
