ood_dataset:
  name: mnist_ood
  dataset_class: ImglistDataset
  transform: mnist_test_standard
  interpolation: bilinear

  batch_size: 128
  shuffle: False
  num_classes: 10
  image_size: 28
  num_workers: '@{num_workers}'

  split_names: [val, nearood, farood]
  val:
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/digits/val_notmnist.txt
  nearood:
    datasets: [notmnist, fashionmnist]
    notmnist:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_notmnist.txt
    fashionmnist:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_fashionmnist.txt
  farood:
    datasets: [texture, cifar10, tin, places365]
    texture:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_texture.txt
    cifar10:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_cifar10.txt
    tin:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_tin.txt
    places365:
      data_dir: ./data/images/
      imglist_pth: ./data/imglist/digits/test_places365.txt
