dataset:
  name: temp
  split_names: [train, val, test]
  num_classes: 1000
  image_size: 256
  num_workers: '@{num_workers}'
  num_gpus: '@{num_gpus}'
  num_machines: '@{num_machines}'
  train:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/temp.txt
    batch_size: 32
    shuffle: True
    interpolation: bilinear
  val:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/temp.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear
  test:
    dataset_class: ImglistDataset
    data_dir: ./data/images/
    imglist_pth: ./data/imglist/temp.txt
    batch_size: 32
    shuffle: False
    interpolation: bilinear
